export enum ActivityTag {
  Sightseeing = "Sightseeing",
  Beach = "Beach",
  Hiking = "Hiking",
  Dining = "Dining",
  Adventure = "Adventure",
  Relaxation = "Relaxation",
  Nightlife = "Nightlife",
  Wildlife = "Wildlife",
  CulturalExperience = "Cultural Experience",
  Festival = "Festival",
  RoadTrip = "Road Trip",
  Camping = "Camping",
  Spa = "Spa",
  Photography = "Photography",
  Entertainment = "Entertainment",
  History = "History",
  FamilyFun = "Family Fun",
  ThemePark = "Theme Park",
}
