export enum ActivityTag {
  Sightseeing = "Sightseeing",
  Beach = "Beach",
  Hiking = "Hiking",
  Shopping = "Shopping",
  Dining = "Dining",
  Museum = "Museum",
  Adventure = "Adventure",
  Relaxation = "Relaxation",
  Nightlife = "Nightlife",
  Wildlife = "Wildlife",
  CulturalExperience = "Cultural Experience",
  Sports = "Sports",
  Festival = "Festival",
  RoadTrip = "Road Trip",
  Camping = "Camping",
  Cruise = "Cruise",
  Spa = "Spa",
  Photography = "Photography",
  Entertainment = "Entertainment",
  History = "History",
  FamilyFun = "Family Fun",
  ThemePark = "Theme Park",
  WaterSports = "Water Sports",
  WinterSports = "Winter Sports"
}
